# Generated by Django 2.2.6 on 2020-04-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
