# Generated by Django 2.2.6 on 2020-04-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='date_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
